#port => 지정하지 않는 경우 : 8080(기본값) => 9090 : ufw를 이용하여 포트 허용
#MVC => Spring FrameWork와 동일 
spring: 
  mvc:
    view:
      prefix: /WEB-INF/view
      suffix: .jsp
    datasource:
      url: jdbc:oracle:thin:@//211.238.142.22:1521/XE
      ursername: hr
      password: happy
      driver-class-name: oracle.jdbc.OracleDriver
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        minimum-idle: 5
        maxmun-pool-size: 10
        idle-timeout: 3000
        max-lifetime: 1800000
        connection-timeout: 30000
#mybatis
mybatis:
  type-aliases-package: com.sist.web.vo
  mapper-locations: mybatis/mapper/*.xml

#JPA
#Security
#WebSocket
#MSA
